---
abstract: 'Light and fluffy object persistence'
author:
  - 'Dave Sherohman <dsheroh@cpan.org>'
build_requires:
  DBI: 0
  FindBin: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101600'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ormlette
requires:
  Carp: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Ormlette
  repository: git://sherohman.org/ormlette
version: 0.01
